### PR TITLE
ROC-7466 Enable local logging of app insights events

### PR DESCRIPTION
**Pull request by andrewwa-kainos**
### JIRA link
https://tools.hmcts.net/jira/browse/ROC-7466

### Change description ###
Enable local logging of app insights events by setting `APPINSIGHTS_INSTRUMENTATIONKEY=STDOUT`
(Also needs change to cmc-integration-tests... https://github.com/hmcts/cmc-integration-tests/pull/425)

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by timja** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/uk/gov/hmcts/cmc/claimstore/appinsights/AppInsights.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/HMCTS/cmc-claim-store/pullRequest?prid=4922555&bid=16288314)

**Comment by daveoh** [comment]
Should the default `APPINSIGHTS_INSTRUMENTATIONKEY` in application.yml be set to `STDOUT`

**Comment by timja** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/uk/gov/hmcts/cmc/claimstore/appinsights/AppInsights.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/HMCTS/cmc-claim-store/pullRequest?prid=4922555&bid=16288314)

**Comment by daveoh** [comment]
Actually, after thinking about this a bit more, I think that we should probably have an explicit boolean to turn this on rather than determining this from the key. This will make it clear how to configure the app without documentation/knowledge.

**Comment by timja** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/uk/gov/hmcts/cmc/claimstore/appinsights/AppInsights.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/HMCTS/cmc-claim-store/pullRequest?prid=4922555&bid=16288314)

**Comment by KiranVarma02** [comment]
> Actually, after thinking about this a bit more, I think that we should probably have an explicit boolean to turn this on rather than determining this from the key. This will make it clear how to configure the app without documentation/knowledge.

**Comment by KiranVarma02** [comment]
sorry i closed PR by mistake :), i reopened it.

**Comment by KiranVarma02** [comment]
> > Actually, after thinking about this a bit more, I think that we should probably have an explicit boolean to turn this on rather than determining this from the key. This will make it clear how to configure the app without documentation/knowledge.

I was going to say i like this idea..

**Comment by daveoh** [comment]
> > > Actually, after thinking about this a bit more, I think that we should probably have an explicit boolean to turn this on rather than determining this from the key. This will make it clear how to configure the app without documentation/knowledge.
> 
> I was going to say i like this idea..

After speaking with @andrewwa-kainos we decided to keep it inline with th front end but add a tech debt to clean this up: https://tools.hmcts.net/jira/browse/ROC-7474

**Comment by timja** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/uk/gov/hmcts/cmc/claimstore/appinsights/AppInsights.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/HMCTS/cmc-claim-store/pullRequest?prid=4922555&bid=16288314)

**Comment by timja** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/uk/gov/hmcts/cmc/claimstore/appinsights/AppInsights.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/HMCTS/cmc-claim-store/pullRequest?prid=4922555&bid=16288314)

**Comment by timja** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/uk/gov/hmcts/cmc/claimstore/appinsights/AppInsights.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/HMCTS/cmc-claim-store/pullRequest?prid=4922555&bid=16288314)

**Comment by timja** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/uk/gov/hmcts/cmc/claimstore/appinsights/AppInsights.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/HMCTS/cmc-claim-store/pullRequest?prid=4922555&bid=16288314)

**Pull request merged**
