### PR TITLE
ROC-7346 fix defendant name changed

### PR DESCRIPTION
**Pull request by karthikkannankainos**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/ROC-7346

### Change description ###

Fix Defendant provided name with Claimant provided and the respective docs that are affected.

### CODE REVIEW

**Comment by timja** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/DataFixSupportController.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/HMCTS/cmc-claim-store/pullRequest?prid=5126444&bid=16850242)

**Comment by timja** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/DataFixSupportController.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/HMCTS/cmc-claim-store/pullRequest?prid=5126444&bid=16850242)

**Comment by andrewwa-kainos** [comment]
This is one-off / throwaway code, right?

**Comment by andrewwa-kainos** [comment]
Can we add a check to verify the defendant has actually changed their name on the claim, to protect us against any typos or other accidental invocations for the wrong claims?

**Comment by karthikkannankainos** [comment]
> This is one-off / throwaway code, right?

Yeah @andrewwa-kainos this is a one off throwaway code.

**Comment by karthikkannankainos** [comment]
> Can we add a check to verify the defendant has actually changed their name on the claim, to protect us against any typos or other accidental invocations for the wrong claims?

I did that check in the previous commit. Now that we have updated the data fix using the SQL update, we are limited to regenerate without verifying. Pls suggest if any way to.

**Comment by timja** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/DataFixSupportController.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/HMCTS/cmc-claim-store/pullRequest?prid=5126444&bid=16850242)

**Comment by timja** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/DataFixSupportController.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/HMCTS/cmc-claim-store/pullRequest?prid=5126444&bid=16850242)

**Comment by timja** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/DataFixSupportController.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/HMCTS/cmc-claim-store/pullRequest?prid=5126444&bid=16850242)

**Comment by timja** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/DataFixSupportController.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/HMCTS/cmc-claim-store/pullRequest?prid=5126444&bid=16850242)

**Pull request merged**
