### PR TITLE
ROC-6843: Remove database sqls and claim store instance

### PR DESCRIPTION
**Pull request by sabahirfan**
### JIRA link (if applicable) ###
[ROC-6843](url)

### Change description ###
This PR removes the claim-store database instances from the code.

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by timja** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/deprectaed/MockedDatabaseConfiguration.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/HMCTS/cmc-claim-store/pullRequest?prid=4876112&bid=16161540)

**Comment by timja** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/deprectaed/MockedDatabaseConfiguration.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/HMCTS/cmc-claim-store/pullRequest?prid=4876112&bid=16161540)

**Comment by timja** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/deprectaed/MockedDatabaseConfiguration.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/HMCTS/cmc-claim-store/pullRequest?prid=4876112&bid=16161540)

**Comment by sabahirfan** [comment]
sure that make sense @ckalista

**Pull request merged**
