### PR TITLE
ROC-3567 Full changeset for replacing references to mobiles with just phone

### PR DESCRIPTION
**Pull request by andrewwa-kainos**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/ROC-3567

### Change description ###
Replaced references in code to mobile phones with just phone numbers

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ? ] Yes
[ ? ] No
```
I don't think so... Would be great to have someone with more experience to double-check

### CODE REVIEW

**Comment by filipczyks** [comment]
In frontend part I have changed 
_mobilePhone_ field to _phone_ instead of _phoneNumber_ in contract. Can we make new field _phone_ also here?

For some temporary time both fields should be supported by API, so we need _mobilePhone_ and _phone_.

Due to CD on this project we need to proceed with more or less this plan:
1. Duplicate _mobilePhone_ field to _phone_ in **claim-store**. 
Write data migration script to support two fields (confirm that?)
Merge **claim-store**.

2. Change _mobilePhone_ to _phone_ on **citizen-frontend**. (only support new field)
Merge **citizen-frontend**

3. For **legal-frontend** no changes are needed, but that needs to be reviewed and confirmed

4. Remove old _mobilePhone_ field in **claim-store**.
Merge **claim-store**.

**Comment by geek-soft** [comment]
What about?

1. Duplicate mobilePhone field to phone in claim-store. (save and read both mobilePhone and phone)
Merge claim-store.

WRITE: frontend:mobilePhone -> claim-store:mobilePhone,phone -> DB:mobilePhone,phone
READ: DB:mobilePhone,phone -> claim-store:mobilePhone,phone -> frontend:mobilePhone,phone

2. Change mobilePhone to phone on citizen-frontend. (save phone only / read mobilePhone and phone)
Merge citizen-frontend.

WRITE: frontend:phone -> claim-store:mobilePhone,phone -> DB:mobilePhone,phone
READ: DB:mobilePhone,phone -> claim-store:mobilePhone,phone -> frontend:mobilePhone,phone

3. Write data migration script to copy mobilePhone to phone. (save and read phone only)
Remove old mobilePhone field in claim-store.
Merge claim-store.

WRITE: frontend:phone -> claim-store:phone -> DB:phone
READ: DB:phone -> claim-store:phone -> frontend:phone

4. Write data migration script to remove mobilePhone field
Merge claim-store.

**Comment by yarpo** [comment]
@geek-soft are you sure it's the best moment to do it?

I mean many of these steps will be gone when we switch to CCD. Why don't we leave it as it is in API until CCD is on?

What's more I don't see too much business value in this work. And this is IMO massive amount of work and a lot of risk.

**Comment by andrewwa-kainos** [comment]
If the point of this exercise was primarily to give us newbies a chance to explore the code - I think that's accomplished. I certainly feel like I understand the architecture better.

If there's doubt about the both the practicality and correctness of merging the changes now, I would recommend rejecting it for now until the situation is clearer.

**Comment by geek-soft** [comment]
Closing for now due to lack of activity.

**Pull request closed without merging**
